### ISSUE TITLE
dt-react-component 5.0 TODO List

### ISSUE THREAD

**Issue by mumiao** [DTStack/dt-react-component#386]
## 更新内容
  **新组件**

   -  [ ]  ContentLayout 组件   #380 
   -  [ ]  Tree Catalog 组件 #193 
     
  **优化**

 -  [ ] 剔除 React Component 的 utils 工具包  #379 
 -  [ ] 重构 SlidePane 组件 #330

**Comment by mumiao** [comment]
DDL：11.10

**Comment by mumiao** [comment]
FilterRules 组件 https://github.com/DTStack/dt-react-component/issues/406   还在迭代，稍等再发

**Comment by mumiao** [comment]
已经发布
